# Generated by Django 4.1.7 on 2023-03-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Project', max_length=16, unique=True)),
                ('link', models.CharField(default='https://github.com/C0deFreak/Project', max_length=40, unique=True)),
                ('worked_on', models.BooleanField(default=False)),
            ],
        ),
    ]
