# Generated by Django 4.1.7 on 2023-03-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_projectdetails_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='link',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='worked_on',
        ),
        migrations.AddField(
            model_name='movie',
            name='age',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default='', max_length=70, unique=True),
        ),
    ]
